### ISSUE TITLE
update package 0.9.12 to 0.10.preview5 problem

### ISSUE THREAD

**Issue by mehmetulukaya** [punker76/MahApps.Avalonia.IconPacks.Testbed#1]
Hello I am trying to use https://github.com/punker76/MahApps.Avalonia.IconPacks.Testbed project with 0.10.preview5 of avalonia but then it is giving errors so I update to back edition 0.9.12 it is working. 

So I try to dive into code and I found the problem between 

https://github.com/AvaloniaUI/Avalonia/blob/86b68ccaced19ed5561e69d97101b8625207fe53/src/Avalonia.Base/AvaloniaProperty.cs#L243 

and 

https://github.com/AvaloniaUI/Avalonia/blob/7baa95a4e789a132591785615bc253f3bd7ec15d/src/Avalonia.Base/AvaloniaProperty.cs#L260

But I think you should change your base code of the

https://github.com/punker76/MahApps.Avalonia.IconPacks.Testbed/blob/ee10e6d56477adaba7dd5548377ac074c55c55bc/src/AvaloniaIconPacks/Core/PackIconControlBase.cs#L217

Is it possible?

**Comment by punker76** [comment]
@mehmetulukaya Thx you for the info about the changes. I updated the main branch and saved the 0.9.12 version [here](https://github.com/punker76/MahApps.Avalonia.IconPacks.Testbed/tree/Avalonia/0.9.12)
